############# English navigation ##############

# main menu
[[main]]
name = "首页"
url = "/"
weight = 1

[[main]]
name = "博客"
url = "blog/"
weight = 2

[[main]]
name = "项目"
url = "project/"
weight = 3

[[main]]
name = "组件"
url = "elements/"
weight = 4

[[main]]
name = "关于"
url = "about/"
weight = 5

[[main]]
weight = 6
name = "更多"
hasChildren = true

[[main]]
parent = "更多"
name = "Contact"
url = "contact/"

[[main]]
parent = "更多"
name = "Categories"
url = "categories/"

[[main]]
parent = "更多"
name = "404 Page"
url = "404/"

[[main]]
parent = "更多"
name = "Policy"
url = "privacy-policy/"

# footer menu
[[footer]]
name = "友链1"
url = "about/"
weight = 1

[[footer]]
name = "齐实呀"
url = "https://qishiya.com/"
weight = 2

[[footer]]
name = "友链3"
url = "privacy-policy/"
weight = 3
