############# English navigation ##############

# main menu
[[main]]
name = "首页"
url = "/"
weight = 1

[[main]]
name = "博客"
url = "blog/"
weight = 2

[[main]]
name = "商店"
url = "store/"
weight = 3

[[main]]
name = "视频"
url = "video/"
weight = 4

[[main]]
name = "关于"
url = "about/"
weight = 5

[[main]]
weight = 6
name = "更多"
hasChildren = true

[[main]]
parent = "更多"
name = "Contact"
url = "contact/"

[[main]]
parent = "更多"
name = "Categories"
url = "categories/"

[[main]]
parent = "更多"
name = "Release"
url = "blog/logs"

[[main]]
parent = "更多"
name = "Policy"
url = "privacy-policy/"

# footer menu
[[footer]]
name = "qishiya"
url = "https://qishiya.com/"
weight = 1

[[footer]]
name = "newbing"
url = "https://www.bing.com/search?q=Bing+AI&showconv=1&FORM=hpcodx"
weight = 2

[[footer]]
name = "bard"
url = "https://bard.google.com/"
weight = 3

[[footer]]
name = "openai"
url = "https://chat.openai.com/"
weight = 4

[[footer]]
name = "yiyan"
url = "https://yiyan.baidu.com/"
weight = 5

[[footer]]
name = "deepl"
url = "https://www.deepl.com/"
weight = 6
