############# English navigation ##############

# main menu
[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
name = "Blog"
pageRef = "/blog"
weight = 2

[[main]]
name = "Elements"
pageRef = "/elements"
weight = 3

[[main]]
weight = 4
name = "Pages"

[[main]]
name = "About"
pageRef = "/about"
weight = 5


[[main]]
parent = "Pages"
name = "Contact"
pageRef = "/contact"

[[main]]
parent = "Pages"
name = "Authors"
pageRef = "/authors"

[[main]]
parent = "Pages"
name = "Categories"
pageRef = "/categories"

[[main]]
parent = "Pages"
name = "404 Page"
pageRef = "/404"


# footer menu
[[footer]]
name = "qishiya"
url = "https://qishiya.com/"
weight = 1

[[footer]]
name = "newbing"
url = "https://www.bing.com/search?q=Bing+AI&showconv=1&FORM=hpcodx"
weight = 2

[[footer]]
name = "bard"
url = "https://bard.google.com/"
weight = 3

[[footer]]
name = "openai"
url = "https://chat.openai.com/"
weight = 4

[[footer]]
name = "yiyan"
url = "https://yiyan.baidu.com/"
weight = 5

[[footer]]
name = "deepl"
url = "https://www.deepl.com/"
weight = 6